=== jan-bajaryn/epam/task13/src/main/resources/temp/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.example.com/orders"
        xmlns:tns="http://by.example.com/orders"
        elementFormDefault="qualified">


    <element name="entities">
        <complexType>
            <sequence>
                <element ref="tns:entity"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="entity" type="tns:Entity" abstract="true"/>
    <element name="order" type="tns:Order" substitutionGroup="tns:entity"/>
    <element name="product" type="tns:Product" substitutionGroup="tns:entity"/>
    <element name="delivery_inf" type="tns:Delivery_inf" substitutionGroup="tns:entity"/>


    <complexType name="Entity">
        <sequence>
            <element name="id" type="int"/>
        </sequence>
    </complexType>

    <complexType name="Order">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="creation" type="date"/>
                    <element name="price" type="int"/>
                    <element name="status" type="string"/>
                    <element name="payment_type" type="int"/>
                    <element name="delivery_inf_id" type="int" minOccurs="0"/>
                    <element name="products" minOccurs="0">
                        <complexType>
                            <sequence>
                                <element name="product" type="int" maxOccurs="unbounded"/>
                            </sequence>
                        </complexType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Delivery_inf">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="delivery_time" type="dateTime"/>
                    <element name="client_name" type="string"/>
                    <element name="address" type="string"/>
                    <element name="phone" type="string"/>
                    <element name="email" type="string" minOccurs="0"/>
                </sequence>
            </extension>
        </complexContent>

    </complexType>
    <complexType name="Product">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="name" type="string"/>
                    <element name="description" type="string"/>
                    <element name="photo_name" type="string"/>
                    <element name="price" type="int"/>

                    <element name="product_type">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="pizza"/>
                                <enumeration value="drink"/>
                                <enumeration value="snack"/>
                            </restriction>
                        </simpleType>
                    </element>

                    <element name="product_size">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="sm"/>
                                <enumeration value="md"/>
                                <enumeration value="lg"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="ingredients" minOccurs="0">
                        <complexType>
                            <sequence>
                                <element name="ingredient" type="string" minOccurs="0" maxOccurs="unbounded"/>
                            </sequence>
                        </complexType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


</schema>

=== jan-bajaryn/epam/task13/src/main/resources/temp/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<entities
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://by.example.com/orders"
        xsi:schemaLocation="http://by.example.com/orders orders.xsd">

    <order>
        <id>2</id>
        <creation>2020-02-25</creation>
        <price>1800</price>
        <status>took</status>
        <payment_type>1</payment_type>
    </order>
    <order>
        <id>3</id>
        <creation>2020-02-24</creation>
        <price>2222</price>
        <status>took</status>
        <payment_type>1</payment_type>
    </order>
    <order>
        <id>4</id>
        <creation>2020-02-24</creation>
        <price>4444</price>
        <status>2</status>
        <payment_type>2</payment_type>
    </order>
    <order>
        <id>5</id>
        <creation>2020-02-24</creation>
        <price>4433</price>
        <status>took</status>
        <payment_type>2</payment_type>
    </order>
    <order>
        <id>6</id>
        <creation>2020-02-24</creation>
        <price>2233</price>
        <status>took</status>
        <payment_type>3</payment_type>
    </order>
    <order>
        <id>7</id>
        <creation>2020-02-24</creation>
        <price>2233</price>
        <status>took</status>
        <payment_type>3</payment_type>
    </order>
    <order>
        <id>8</id>
        <creation>2020-02-24</creation>
        <price>3456</price>
        <status>took</status>
        <payment_type>2</payment_type>
    </order>
</entities>
