=== jan-bajaryn/epam/task13/src/main/resources/totest/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.example.com/orders"
        xmlns:tns="http://by.example.com/orders"
        elementFormDefault="qualified">

    <!--    <element name="students">-->
    <!--        <complexType>-->
    <!--            <sequence>-->
    <!--                <element name="order"-->
    <!--                         type="tns:Order"-->
    <!--                         minOccurs="2"-->
    <!--                         maxOccurs="unbounded"/>-->
    <!--            </sequence>-->
    <!--        </complexType>-->
    <!--    </element>-->

    <complexType name="Entity">
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="ID-\d{1,10}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>


    <element name="orders">
        <complexType>
            <sequence>
                <element name="order" type="tns:Order" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Order">
        <all>
            <element name="creation" type="dateTime"/>
            <element name="total_price" type="int"/>
            <element name="status" type="string"/>
            <element name="payment_type" type="int"/>
            <element name="delivery_inf" type="tns:Delivery_inf" minOccurs="0"/>
            <element name="products">
                <complexType>
                    <sequence>
                        <element name="product" type="tns:Product" minOccurs="0" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
        </all>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="int">
                    <!--                <restriction base="ID">-->
                    <!--                    <pattern value="[\w-]+"></pattern>-->
                    <minInclusive value="0"/>
                    <maxInclusive value="999999999"/>
                </restriction>
            </simpleType>
        </attribute>
        <!--        <attribute name="id">-->
        <!--            <simpleType>-->
        <!--                <restriction base="int">-->
        <!--                    &lt;!&ndash;                <restriction base="ID">&ndash;&gt;-->
        <!--                    &lt;!&ndash;                    <pattern value="[\w-]+"></pattern>&ndash;&gt;-->
        <!--                    <minInclusive value="0"/>-->
        <!--                    <maxInclusive value="999999999"/>-->
        <!--                </restriction>-->
        <!--            </simpleType>-->
        <!--        </attribute>-->

    </complexType>
    <complexType name="Delivery_inf">
        <all>
            <element name="delivery_time" type="dateTime"/>
            <element name="client_name" type="string"/>
            <element name="address" type="string"/>
            <element name="phone" type="string"/>
            <element name="email" type="string" minOccurs="0"/>
        </all>
    </complexType>
    <complexType name="Product">
        <complexContent>
            <extension base="tns:Entity">
                <all>
                    <element name="name" type="string"/>
                    <element name="description" type="string"/>
                    <element name="photo_name" type="string"/>
                    <element name="price" type="int"/>

                    <element name="product_size">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="sm"/>
                                <enumeration value="md"/>
                                <enumeration value="lg"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="ingredients" minOccurs="0">
                        <complexType>
                            <sequence>
                                <element name="ingredient" type="string" minOccurs="0" maxOccurs="unbounded"/>
                            </sequence>
                        </complexType>
                    </element>
                </all>
                <attribute name="product_type" use="optional" default="pizza">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="pizza"/>
                            <enumeration value="drink"/>
                            <enumeration value="snack"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>


        <!--        <attribute name="id" use="required">-->
        <!--            <simpleType>-->
        <!--                <restriction base="int">-->
        <!--                    &lt;!&ndash;                <restriction base="ID">&ndash;&gt;-->
        <!--                    &lt;!&ndash;                    <pattern value="[\w-]+"></pattern>&ndash;&gt;-->
        <!--                    <minInclusive value="0"/>-->
        <!--                    <maxInclusive value="999999999"/>-->
        <!--                </restriction>-->
        <!--            </simpleType>-->
        <!--        </attribute>-->


    </complexType>
</schema>

=== jan-bajaryn/epam/task13/src/main/resources/totest/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<orders
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://by.example.com/orders"
        xsi:schemaLocation="http://by.example.com/orders orders.xsd">

    <order id="1">
        <products>
            <product id="ID-1">
                <name>Margarita</name>
                <description>Very good classic pizza</description>
                <photo_name>Margarita.jpg</photo_name>
                <price>900</price>
                <product_size>md</product_size>
                <ingredients>
                    <ingredient>Cheese</ingredient>
                    <ingredient>Tomato</ingredient>
                    <ingredient>Bacon</ingredient>
                </ingredients>
            </product>
            <product id="ID-2" product_type="drink">
                <name>Coca-cola</name>
                <description>Classical american drink</description>
                <photo_name>Coca-cola.jpg</photo_name>
                <price>300</price>

                <product_size>sm</product_size>
            </product>
        </products>
        <creation>2020-02-24T09:30:10.5</creation>
        <total_price>1200</total_price>
        <status>waiting</status>
        <payment_type>1</payment_type>
    </order>
    <order id="2">
        <products>
            <product id="ID-3">
                <name>Bacon-and-cheese</name>
                <description>Pizza with bacon and cheese</description>
                <photo_name>Bacon-and-cheese.jpg</photo_name>
                <price>1800</price>
                <product_size>lg</product_size>
                <ingredients>
                    <ingredient>Cheese</ingredient>
                    <ingredient>Mushroom</ingredient>
                    <ingredient>Bacon</ingredient>
                </ingredients>
            </product>
        </products>
        <creation>2020-02-25T09:30:10.5</creation>
        <total_price>1800</total_price>
        <status>waiting</status>
        <payment_type>1</payment_type>
        <delivery_inf>
            <delivery_time>2002-05-30T09:30:10.5</delivery_time>
            <client_name>Jan</client_name>
            <address>Lenina 30, 30</address>
            <phone>+375 29 345 34 34</phone>
            <email>abcd@gmail.com</email>
        </delivery_inf>
    </order>
</orders>
